- type: aQSetting
  id: SS14
  weight: 10
  name: "Space Station 14"

- type: aQSetting
  id: OS14
  weight: 9
  name: "Orbital Station 14"

- type: aQSetting
  id: EP
  weight: 8
  name: "Elysium Prime"